/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_6 (
    input [5:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] shift
  );
  
  
  
  reg [3:0] xb;
  
  always @* begin
    xb = $signed(b[0+3-:4]);
    
    case (alufn[0+1-:2])
      2'h0: begin
        shift = $signed(a) << xb;
      end
      2'h1: begin
        shift = $signed(a) >> xb;
      end
      2'h3: begin
        shift = $signed(a) >>> xb;
      end
      default: begin
        shift = 1'h0;
      end
    endcase
  end
endmodule
