/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module lives_3 (
    input [15:0] num,
    output reg [2:0] led
  );
  
  
  
  always @* begin
    
    case (num)
      1'h0: begin
        led = 3'h0;
      end
      1'h1: begin
        led = 3'h1;
      end
      2'h2: begin
        led = 3'h3;
      end
      2'h3: begin
        led = 3'h7;
      end
      default: begin
        led = 3'h7;
      end
    endcase
  end
endmodule
