/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module speeds_2 (
    input [2:0] num,
    output reg [23:0] speed
  );
  
  
  
  always @* begin
    
    case (num)
      1'h0: begin
        speed = 24'h400000;
      end
      1'h1: begin
        speed = 24'h3a0000;
      end
      2'h2: begin
        speed = 24'h300800;
      end
      2'h3: begin
        speed = 24'h2cf000;
      end
      3'h4: begin
        speed = 24'h220000;
      end
      3'h5: begin
        speed = 24'h1af000;
      end
      3'h6: begin
        speed = 24'h120000;
      end
      3'h7: begin
        speed = 24'h0f0000;
      end
      default: begin
        speed = 24'h4a0000;
      end
    endcase
  end
endmodule
